language: go

go:
  - 1.13.x

sudo: required

services:
  - docker

before_install:
  - go get -u github.com/golang/lint/golint
  - export PATH=$PWD/bin:$PATH

install:
  - go mod tidy

script:
  - golint -set_exit_status
  - go vet -v
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
